### PR TITLE
optimized the pop ups for foreign languages

### PR DESCRIPTION
**Pull request by LeiSurrre**
Added a condition for Safari and mobile devices to find a div tag after
finishing loading the page.

### CODE REVIEW

**Comment by LeiSurrre** [comment]
The reason why the pop ups are not showing up on Safari and mobile devices is because the JS is running before the page is loaded. And it is the opposite way for Chrome and Firefox. So adding an "if" statement to check either conditions solves the problem.
@carloscanas

**Comment by carloscanas** [comment]
@LeiSurrre Awesome job! :shipit:

**Comment by LeiSurrre** [comment]
Fixed one variable not defined bug, and optimized the shadow for the notification window.
@carloscanas

**Comment by carloscanas** [comment]
:shipit:

**Pull request merged**
