### PR TITLE
Mobile support site branch

### PR DESCRIPTION
**Pull request by thuvejan**
@carloscanas Changed and fixed some CSS for the phone view of the support site to provide a better user experience.

### CODE REVIEW

**Comment by carloscanas** [comment]
@thuvejan  After testing :shipit:

**Comment by thuvejan** [comment]
@carloscanas Updated with login footer for phone view. Tested on production.

**Comment by carloscanas** [comment]
@thuvejan :shipit:

**Comment by thuvejan** [comment]
Removed footer sign in menu commits due to template component issue.

**Pull request merged**
