### PR TITLE
Remove the reporting ads form

### PR DESCRIPTION
**Pull request by LeiSurrre**
Removed the form for reporting ads on the ticket submission page.

### CODE REVIEW

**Comment by LeiSurrre** [comment]
@carloscanas

**Comment by carloscanas** [comment]
@LeiSurrre This is wrong. The form should still appear in its entirety if accessed via direct link. Starting on line 156 you remove code that should still be left.

**Comment by LeiSurrre** [comment]
@carloscanas I have readded the form to the page, and it will only show up when users are directly linked to the page with that id.

**Comment by carloscanas** [comment]
:shipit:

**Pull request merged**
